languageCode = "en"
languageName = "English"
weight = 1

title = "Andrei-Carlo Papuc"
copyright = "© 2023 Andrei-Carlo Papuc"

[params]
isoCode = "en"
displayName = "EN"
rtl = false

dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
description = "Personal website of Andrei-Carlo Papuc. MSc Robotics at TU Delft"

[author]
name = "Andrei-Carlo Papuc"
image = "img/author-modified.jpg"
# headline = "I'm only human"
bio = "Personal website of Andrei-Carlo Papuc. MSc Robotics at TU Delft"
links = [
    { email = "mailto:andrejcarlop@gmail.com" },
    #   { link = "https://link-to-some-website.com/" },
    #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #   { apple = "https://www.apple.com" },
    #   { blogger = "https://username.blogspot.com/" },
    #   { codepen = "https://codepen.io/username" },
    #   { dev = "https://dev.to/username" },
    #   { discord = "https://discord.gg/invitecode" },
    #   { dribbble = "https://dribbble.com/username" },
    #   { facebook = "https://facebook.com/username" },
    #   { flickr = "https://www.flickr.com/photos/username/" },
    #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/andrejcarlo" },
    #   { gitlab = "https://gitlab.com/username" },
    #   { google = "https://www.google.com/" },
    #   { hashnode = "https://username.hashnode.dev" },
    #   { instagram = "https://instagram.com/username" },
    #   { keybase = "https://keybase.io/username" },
    #   { kickstarter = "https://www.kickstarter.com/profile/username" },
    #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/andreicarlopapuc" },
    #   { mastodon = "https://mastodon.instance/@username" },
    #   { medium = "https://medium.com/username" },
    #   { microsoft = "https://www.microsoft.com/" },
    #   { orcid = "https://orcid.org/userid" },
    #   { patreon = "https://www.patreon.com/username" },
    #   { pinterest = "https://pinterest.com/username" },
    #   { reddit = "https://reddit.com/user/username" },
    #   { researchgate = "https://www.researchgate.net/profile/username" },
    #   { slack = "https://workspace.url/team/userid" },
    #   { snapchat = "https://snapchat.com/add/username" },
    #   { soundcloud = "https://soundcloud.com/username" },
    #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #   { steam = "https://steamcommunity.com/profiles/userid" },
    #   { telegram = "https://t.me/username" },
    #   { tiktok = "https://tiktok.com/@username" },
    #   { tumblr = "https://username.tumblr.com" },
    #   { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/andrejcarlo" },
    #   { whatsapp = "https://wa.me/phone-number" },
    #   { youtube = "https://youtube.com/username" },
]
